### ISSUE TITLE
Maps using the new BPM change method are played at the wrong BPM

### ISSUE THREAD

**Issue by noam15A** [AllPoland/ArcViewer#20]
Found this trying to view a map I uploaded: https://beatsaver.com/maps/32d5b
It uses the new BPM change format (BPMInfo.dat file) and has a BPM change at 0:19 which simply doesn't happen when viewed in ArcViewer

**Comment by AllPoland** [comment]
The BPMInfo.dat is irrelevant to ArcViewer. BPM events are stored in the difficulty file.
In this case, the issue is that the current release of ArcViewer doesn't read V2 BPM events, which is fixed in development and will be out soon.
