### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by ibillingsley** [AllPoland/ArcViewer#21]
It would be nice if you could provide the folder/zip path or BeatSaver ID to the desktop app via command line.
That would allow other desktop apps like [BSManager](https://github.com/Zagrios/bs-manager) or [Beatlist](https://github.com/ranmd9a/beatlist) to integrate with ArcViewer to preview songs with it.

**Comment by AllPoland** [comment]
Just added this in v0.3.5, and updated the URL Argument Docs to include info on it.
https://github.com/AllPoland/ArcViewer/wiki/URL-Argument-Docs#command-line-arguments
