### ISSUE TITLE
Feature Request - handle Lock Direction in ArcViewer

### ISSUE THREAD

**Issue by MitchSirco** [AllPoland/ArcViewer#23]
Hello there, i don't know if this is the right place to submit a feature request, but here we are:

## Summary of Suggestion: 
Add a way to see, when the map "locks direction for a laser".

(soz, for not being embed links)
## How it looks in Chromapper: (idea)
[Video in Chromapper](https://cdn.discordapp.com/attachments/996396925471424553/1125033242454655096/Recording_2023-07-02_135734.mp4) (shows that the lasers are slowing down, and speeding up, while being in the "lock direction" state)

## How it looks in ArcViewer: (current State, v0.3.5)
[Video in Arcviewer](https://cdn.discordapp.com/attachments/996396925471424553/1125033750703648828/20230702-1201-28.5328114.mp4) (ArcViewer shows the lasers, but no "lock direction" state is handled, making them go party mode)

Cheers.

**Comment by AllPoland** [comment]
LockRotation is a feature of Chroma, and luckily I already had Chroma support all developed when you made this, and it's been added in v0.4.0. LockRotation should now work properly among most other Chroma features.
