### ISSUE TITLE
Unable to parse .dat

### ISSUE THREAD

**Issue by Elecast2** [AllPoland/ArcViewer#30]
https://beatsaver.com/maps/34a3d

Not sure why I get this error with the map, didn't find errors in the json

**Comment by AllPoland** [comment]
You have two instances of `"_color": 1` in the `_customData` of lighting events. ArcViewer expects these to be valid color objects. Unfortunately fixing this for every possible case would require a full refactor of Json processing which isn't feasible right now.

**Comment by AllPoland** [comment]
Just made a fix on dev, will be fixed with the next version release.

**Comment by Elecast2** [comment]
Sure, and thanks for pointing out the errors in the json, I couldn't find them
