### ISSUE TITLE
Profile pictures in GIF format do not load.

### ISSUE THREAD

**Issue by DizzyJune** [AllPoland/ArcViewer#36]
Profile pictures in GIF format do not load, you can see in this replay, or any others by me https://allpoland.github.io/ArcViewer/?scoreID=8776234

**Comment by AllPoland** [comment]
Known issue, Unity doesn't have native support for GIFs, so adding support for this would involve manually decoding the GIF and reading each frame as separate images. Given how much effort this really is, it's not super high on my to-do list at the moment.

**Comment by AllPoland** [comment]
Added in v0.5.3
