### ISSUE TITLE
Strange head movement on BL replay

### ISSUE THREAD

**Issue by 2010Bronks** [AllPoland/ArcViewer#42]
### Describe the bug:
*While viewing my BL replay i noticed that FP cam randomly jitters.*

### How to Reproduce:

- *Open replay*
- *Enable FP cam*
- *Watch some of my time codes: 1:04,  1:12, 1:25, 1:35, 1:55*

### Expected behavior:
*FP cam should not jitter like that since i didn't shake my head like that.*

### Build Info:
 - Platform: *Chrome*
 - Version: *116.0.5845.111*

### Additional context:
Link to replay: https://allpoland.github.io/ArcViewer/?scoreID=8819614
Video that shows that issue: https://www.youtube.com/watch?v=FmBI0Li6MAc

**Comment by AllPoland** [comment]
Fixed in 0.5.4
