### ISSUE TITLE
Old replay used even if score was improved

### ISSUE THREAD

**Issue by Solaris9** [AllPoland/ArcViewer#46]
### Describe the bug:
Old replays seem to be used even if you've improved the score.

### How to Reproduce:
Steps to reproduce the behaviour:

- View https://allpoland.github.io/ArcViewer/?scoreID=8910744
- View https://replay.beatleader.xyz/?scoreId=8910744
- Notice how ArcViewer uses the old 1 year replay (3 miss, 93%) while BeatLeader uses the newest replay (FC, 95%)

### Expected behavior:
- It should use the newest replay.

### Build Info:
Safari 16.6
MacOS Ventura 13.5.1 on M1 MacBook
ArcViewer Web 0.5.5

### Additional context:
Chrome seems to use the newest replay so perhaps a caching issue as I previously watched my old replay before improving the score?

**Comment by Solaris9** [comment]
I restarted my browser and it seems to use the latest replay now, so I suppose it's definitely caching the replay? I'm not sure if I had ArcViewer open when I submitted the new score as it was 6 hours ago, or if it cached the old replay when I first watched it and when it requested the score from the BL API it used the existing cached replay since the BSOR url doesn't change so it wouldn't fetch the new replay.

**Comment by AllPoland** [comment]
Works fine for me, so almost certainly a cache issue.
ArcViewer doesn't control the cache, that's all handled on the browser end, so there's not much I could do even if I wanted to.
