### ISSUE TITLE
New Discord links are no longer considered valid URLs 

### ISSUE THREAD

**Issue by ModdingPink** [AllPoland/ArcViewer#52]
### Describe the bug:
The new discord URLs are not considered "valid".
<img width="326" alt="image" src="https://github.com/AllPoland/ArcViewer/assets/62712899/c36b9d5c-4bdf-4f35-b8c8-b2bfacf29e3d">

### How to Reproduce:

- Find a zip on Discord
- Copy Link
- Attempt to put it into ArcViewer through either the URL or the initial page

### Expected behavior:
The zip link is loaded normally

### Build Info:
 - Platform: Windows, Chrome
 - Version: v0.5.8

**Comment by AllPoland** [comment]
Fixed in v0.5.9 👍🏻
