### ISSUE TITLE
[Suggestion, not really a bug] Changing minimum speed from 0 to 0.05

### ISSUE THREAD

**Issue by CodeSoftGit** [AllPoland/ArcViewer#55]
Yeah, 0 speed basically just pauses it so i think it would just be better to make it 0.05

**Comment by AllPoland** [comment]
1: Because of the fact that you can type in any decimal time you want, it doesn't really make sense to put an arbitrary minimum on this

2: It's kinda funny though :)

**Comment by JiveOff** [comment]
> Yeah, 0 speed basically just pauses it so i think it would just be better to make it 0.05

Well, apparently now, putting at 0 speed doesn't pause, it desynchronizes the entire song.
@AllPoland can you have another look?

**Comment by AllPoland** [comment]
> > Yeah, 0 speed basically just pauses it so i think it would just be better to make it 0.05
> 
> Well, apparently now, putting at 0 speed doesn't pause, it desynchronizes the entire song. @AllPoland can you have another look?

Able to replicate this (among other issues) on some browsers, guess it depends on how each browser implements audio. I'll throw a 0.01x minimum on it in the next update.
