### ISSUE TITLE
Desktop viewer unable to load maps with "+" in path (Windows)

### ISSUE THREAD

**Issue by ibillingsley** [AllPoland/ArcViewer#60]
### Describe the bug:
With ArcViewer.exe I am unable to preview local maps that contain a `+` character in the song folder name.
Error: "Unable to load song file!" is shown (not "That file or directory doesn't exist!")

Example map: https://beatsaver.com/maps/1ffbe

### How to Reproduce:

- Open ArcViewer.exe
- Paste map path containing `+`, e.g. `C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\1ffbe (CTRL + ALT + DEL [Fitbeat] - Scarladore)`
- Error "Unable to load song file!" is shown

### Expected behavior:
Should be able to preview the map.

### Build Info:
 - Platform: Windows 10
 - Version: ArcViewer.exe v0.6.0

### Additional context:
- Same issue occurs if I browse via "Open file explorer" and select the info.dat file.
- Same issue occurs if I provide the path via command line argument.
- Also occurs if `+` is in a parent folder name instead of song folder.
- Attached log file [Player.log](https://github.com/AllPoland/ArcViewer/files/14549067/Player.log)

**Comment by AllPoland** [comment]
Should be fixed in 0.6.1, lmk if any file paths are still broken (or got broken lmao)

**Comment by ibillingsley** [comment]
Thanks, I tried paths with `+` `&` `%` and they all work so far.
