### ISSUE TITLE
Incorrect saber colors on modded map with left-handed mode

### ISSUE THREAD

**Issue by f1amy** [AllPoland/ArcViewer#67]
### Describe the bug:
On a modded map that can change block and saber colors mid-game, replay viewer does not handle left-handed mode, resulting in swapped saber colors with blocks they're hitting.
Also, even if blocks can change colors in a replay, sabers do not change colors at all (another issue).

### How to Reproduce:

- Go to replay of a modded map that changes block colors with player left-handed setting enabled
- Play
- See that sabers hit wrong colored blocks and there is no bad cut

### Expected behavior:
Sabers should hit same block colors

### Build Info:
 - Platform: Windows/Chrome
 - Version: v0.6.2

### Additional context:
https://allpoland.github.io/ArcViewer/?scoreID=16423133

![image](https://github.com/user-attachments/assets/fb535640-2824-434f-89ab-52f44591f24d)
![image](https://github.com/user-attachments/assets/ca6e6d52-6218-4905-9fd8-92f54fe8db39)

**Comment by AllPoland** [comment]
I've added dynamic saber colors in 0.6.3, so now they'll change to match the next notes' colors when a map uses chroma

**Comment by f1amy** [comment]
It's fixed now, thanks!
